### ISSUE TITLE
Rails 5 deprecation warning.

### ISSUE THREAD

**Issue by kevintyll** [premailer/actionmailer_inline_css#25]
Using `alias_method_chain` is deprecated in Rails 5.

**Comment by roryokane** [comment]
This is the full deprecation message I see:

> DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /Users/roryokane/path/to/backend/config/application.rb:8)

The message is annoying because it is printed when running *any* `rails` command – not just `rails server` or `rails console`, which have a lot of output of their own, but even `rails routes` and `rails middleware`, whose only function is to output something. The deprecation message clutters up the output, especially when wrapped to fit the terminal window:

```
$ rails middleware
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepen
d instead. From module, you can access the original method using super. (called 
from <top (required)> at /Users/roryokane/longer/path/to/backend/config/applicat
ion.rb:8)
use Rack::Sendfile
use Rack::Cors
use ActionDispatch::Static
…
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
```

Another bad thing about the deprecation message is that it doesn’t identify which included gem is the cause – the referenced line in my app is just `Bundler.require(*Rails.groups)`. It took quite some searching to figure out that this gem was the culprit. The poor wording of the error message is not this gem’s fault, but it still provides a bad user experience.

**Comment by roryokane** [comment]
Link: @kevintyll’s pull request “[Eliminate Rails 5 deprecation warning.](https://github.com/premailer/actionmailer_inline_css/pull/26)” fixes this issue.
